- workload=cloudlab_unet3d_h100
- ++workload.workflow.generate_data=False
- ++workload.workflow.train=True
- ++workload.dataset.num_files_train=2000
- ++workload.dataset.data_folder=unet3d_data
- ++workload.workflow.profiling=False
- ++workload.profiling.profiler=none
